name: Continuous Deployment

on:
  push:
    branches:
      - main
      - beta
      - development
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node_modules-
      - name: Setup
        run: make setup
        env:
          CI: true
          HUSKY: 0
      - name: Build
        run: make build
        env:
          CI: true
          HUSKY: 0
      - name: Release
        run: make release
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: true
          HUSKY: 0
